routes/web.php
	Route::post('campaign/sms/storemultioffertemplate/{campaign_type_id}/{template_id}', ['as' => 'campaign.sms.storemultioffertemplate' , 'uses' => 'SMS\campaign\SmsController@storeMultiOfferTemplate']);


	//Get field list by template id
	Route::get('get-field-template-list','SMS\campaign\CampaignController@getFieldTemplateList');

	//Feilds resource
	Route::resource('fields', 'SMS\FieldController');

	//SMS Template resource
	Route::resource('templates', 'SMS\TemplateController');

	//Rule Type resource
	Route::resource('ruletypes', 'SMS\rule\RuleTypeController');

	//Rule resource
	//Route::resource('rules', 'rule\RuleController');

	//Vocuhers resource
	Route::resource('vouchers', 'SMS\campaign\VoucherController');
	//Get template list
	Route::get('voucher/get-offer-list', 'SMS\campaign\VoucherController@getOfferList');
	//Get Offer Cashback list
	Route::get('voucher/get-offer-cashback', 'SMS\campaign\VoucherController@getOfferCashback');
	Route::get('voucher/fetch_data', 'SMS\campaign\VoucherController@fetch_data');
	Route::get('voucher/upload/create', ['as' => 'voucher.upload.create' , 'uses' => 'SMS\campaign\VoucherController@uploadVoucherCodeCreate']);
	Route::post('voucher/upload/store', ['as' => 'voucher.upload.store' , 'uses' => 'SMS\campaign\VoucherController@uploadVoucherCodeStore']);
	Route::get('voucher/all/edit', ['as' => 'voucher.all.edit' , 'uses' => 'SMS\campaign\VoucherController@allVoucherCodeEdit']);
	
	Route::post('voucher/all/update', ['as' => 'voucher.all.update' , 'uses' => 'SMS\campaign\VoucherController@allVoucherCodeUpdate']);
	Route::get('voucher/all/view', ['as' => 'delete.all.view' , 'uses' => 'SMS\campaign\VoucherController@allVoucherCodeDeleteView']);
	
	Route::post('voucher/all/viewUpdate', ['as' => 'delete.all.update' , 'uses' => 'SMS\campaign\VoucherController@allVoucherCodeDeleteUpdate']);

	Route::get('voucher/list', ['as' => 'voucher.list' , 'uses' => 'SMS\campaign\VoucherController@index']);

	//Campaign Feilds resource
	Route::resource('campaign-fields', 'SMS\campaign\CampaignFieldController');
	
	//Campaign rule create 
	Route::get('campaign/setting/create', ['as' => 'campaign.setting.create' , 'uses' => 'SMS\campaign\SettingController@create']);
	//Campaign rule store 
	Route::post('campaign/setting/store/{id?}', ['as' => 'campaign.setting.store' , 'uses' => 'SMS\campaign\SettingController@store']);
	
	//Campaign rule create 
	Route::get('campaign/redirect', ['as' => 'campaign.redirect' , 'uses' => 'SMS\campaign\SettingController@createRidrect']);
	//Campaign rule store 
	Route::post('campaign/redirectStore/{id?}', ['as' => 'campaign.redirectStore' , 'uses' => 'SMS\campaign\SettingController@storeRidrect']);


    //Incoming SMS 
	Route::get('report/incoming/list', ['as' => 'report.incoming.list' , 'uses' => 'SMS\campaign\ReportController@incomingReportList']);
	
	//Outgoing SMS 
	Route::get('report/outgoing/list', ['as' => 'report.outgoing.list' , 'uses' => 'SMS\campaign\ReportController@outgoingReportList']);
	
	//Whatsapp SMS 
	//Route::get('report/whatsapp/list', ['as' => 'report.whatsapp.list' , 'uses' => 'SMS\campaign\ReportController@whatsappReportList']);
	
	//Whatsapp SMS 
	Route::get('report/list/{id}', ['as' => 'report.whatsapp.list' , 'uses' => 'SMS\campaign\ReportController@whatsappImageView']);
	
    //reward List 
	Route::get('rewardcode/list', ['as' => 'rewardcode.list' , 'uses' => 'SMS\campaign\CampaignController@rewardcodeList']);
	
	//Issue Pnnel List 
	Route::get('issue/panel/list', ['as' => 'issue.panel.list' , 'uses' => 'SMS\campaign\ReportController@issuePanelList']);

	

	//reward List 
	Route::get('rewardcode/dashboard/list', ['as' => 'rewardcode.dashbaord.list' , 'uses' => 'SMS\campaign\CampaignController@rewardcodeDashboardList']);
	

	//reward List 
	Route::get('vouchercode/dashboard/list', ['as' => 'vouchercode.dashbaord.list' , 'uses' => 'SMS\campaign\CampaignController@vouchercodeDashboardList']);
    
	
});
Route::get('admin/outgoing/download-outgoing-excel', 'SMS\campaign\ReportController@allOutgoingDownload')->name('outgoing.download-outgoing-excel');

Route::get('admin/incoming/download-incoming-excel', 'SMS\campaign\ReportController@allIncomingDownload')->name('incoming.download-incoming-excel');
//Get field list by template id
Route::get('get-keyword-data','SMS\campaign\CampaignController@getKeywordData');
    
//Get field list by template id
Route::get('get-whatsapp-data','Whatsapp\WhatsAppController@getWhatsAppData');

//Whatsapp SMS 
Route::get('send-sms-template/{incoming_msg_id?}', 'SMS\campaign\SmsController@sendSmsTemplate');

//Whatsapp SMS 
Route::get('send-sms-second-template', 'SMS\campaign\SmsController@sendSmsSecondTemplate');

//Whatsapp SMS 
Route::get('send-sms-voucher-recharge-template', 'SMS\campaign\SmsController@sendVoucherRechargeBasedTemplate');
//Whatsapp SMS 
Route::get('send-whatsapp-template/{incoming_msg_id?}', 'Whatsapp\campaign\SmsController@sendWhatsappTemplate');


Route::get('validate-mobile-per-promotion/{campaign_id?}/{mobile_no?}', 'SMS\campaign\SmsController@validateMobilePerPromotion');


//Whatsapp


Route::group(['middleware'=>['admin'],'prefix'=> 'admin/whatsapp/'], function (){

	/*Route::get('register', 'AuthController@register');
	Route::post('post-register', 'AuthController@postRegister'); */
	Route::get('dashboard', 'Whatsapp\AuthController@dashboard'); 
/*	Route::get('logout', 'AuthController@logout');*/
    Route::post('dashboard', 'Whatsapp\AuthController@dashboard');
    //Campaign type resource
	Route::resource('campaignextesions', 'Whatsapp\campaign\CampaignExtensionController');
    //Issue Pnnel List 
	Route::get('issue/panel/list', ['as' => 'issue.panel.list' , 'uses' => 'Whatsapp\campaign\ReportController@issuePanelList']);

    //Offer type resource
	Route::resource('cashbacktypes', 'Whatsapp\campaign\CashbackTypeController');


	//Get cashback list
	Route::get('cashbacktype/get-cashbacktype-list', 'Whatsapp\campaign\CashbackTypeController@getCashbackTypeList');

	//Campaign type resource
	Route::resource('whatsappcampaigntypes', 'Whatsapp\campaign\CampaignTypeController');
	
	//Offer type resource
	Route::resource('whatsappoffers', 'Whatsapp\campaign\OfferTypeController');
	
	//Get template list
	Route::get('whatsappcampaigntype/get-template-list', 'Whatsapp\campaign\CampaignTypeController@getTemplateList');
	

	//Get status change
    Route::get('changeStatus', 'AuthController@changeStatus');

    //Campaign resource
	Route::resource('whatsappcampaigns', 'Whatsapp\campaign\CampaignController');
	
	//Campaign rule 
	Route::get('campaign/stats/{campaign_id}', ['as' => 'whatsappcampaign.stats' , 'uses' => 'Whatsapp\campaign\CampaignController@whatsappstats']);

	//Campaign rule 
	Route::get('campaign/rules/index/{campaign_id}', ['as' => 'whatsappcampaign.rules.index' , 'uses' => 'Whatsapp\rule\RuleController@index']);
	//Campaign rule show 
	Route::get('campaign/rules/show/{campaign_id}/{rule_id}', ['as' => 'whatsappcampaign.rules.show' , 'uses' => 'Whatsapp\rule\RuleController@show']);
	//Campaign rule edit 
	Route::get('campaign/rules/edit/{campaign_id}/{rule_id}', ['as' => 'whatsappcampaign.rules.edit' , 'uses' => 'Whatsapp\rule\RuleController@edit']);

	//Campaign rule create 
	
	Route::get('campaign/rules/create/{campaign_id}', ['as' => 'campaign.rules.create' , 'uses' => 'Whatsapp\rule\RuleController@create']);
	//Campaign rule store 
	Route::post('campaign/rules/store/{campaign_id}', ['as' => 'campaign.rules.store' , 'uses' => 'Whatsapp\rule\RuleController@store']);
	//Campaign rule update 
	Route::PATCH('campaign/rules/update/{rule_id}/{campaign_id}', ['as' => 'campaign.rules.update' , 'uses' => 'Whatsapp\rule\RuleController@update']);

	//Campaign sms Template list
	Route::get('campaign/smstemp/index/{campaign_id}', ['as' => 'campaign.sms.index' , 'uses' => 'Whatsapp\campaign\SmsController@index']);
	//Campaign sms Template show
	Route::get('campaign/sms/show/{campaign_id}/{sms_id}', ['as' => 'campaign.sms.show' , 'uses' => 'Whatsapp\campaign\SmsController@show']);
	//Campaign sms Template edit
	Route::get('campaign/sms/edit/{campaign_id}/{sms_id}', ['as' => 'campaign.sms.edit' , 'uses' => 'Whatsapp\campaign\SmsController@edit']);

	//Campaign sms Template create
	Route::get('campaign/sms/create/{campaign_type_id}/{template_id}', ['as' => 'whatsappcampaign.sms.create' , 'uses' => 'Whatsapp\campaign\SmsController@create']);
	//Campaign sms Template store
	Route::post('campaign/sms/store/{campaign_type_id}/{template_id}', ['as' => 'whatsappcampaign.sms.store' , 'uses' => 'Whatsapp\campaign\SmsController@store']);
	//Campaign sms Template update
	Route::PATCH('campaign/sms/update/{sms_id}/{campaign_id}', ['as' => 'whatsappcampaign.sms.update' , 'uses' => 'Whatsapp\campaign\SmsController@update']);

	//Campaign multioffercode sms Template Create

	Route::get('campaign/sms/createmultioffertemplate/{campaign_type_id}/{template_id}', ['as' => 'whatsappcampaign.sms.createmultioffertemplate' , 'uses' => 'Whatsapp\campaign\SmsController@createMultiOfferTemplate']);
	//Campaign sms Template store
	Route::post('campaign/sms/storemultioffertemplate/{campaign_type_id}/{template_id}', ['as' => 'whatsappcampaign.sms.storemultioffertemplate' , 'uses' => 'Whatsapp\campaign\SmsController@storeMultiOfferTemplate']);


	//Get field list by template id
	Route::get('get-field-template-list','Whatsapp\campaign\CampaignController@getFieldTemplateList');

	//Feilds resource
	Route::resource('whatsappfields', 'Whatsapp\FieldController');

	//SMS Template resource
	Route::resource('whatsapptemplates', 'Whatsapp\TemplateController');

	//Rule Type resource
	Route::resource('whatsappruletypes', 'Whatsapp\rule\RuleTypeController');

	//Rule resource
	//Route::resource('rules', 'rule\RuleController');

	//Vocuhers resource
	Route::resource('whatsappvouchers', 'Whatsapp\campaign\VoucherController');

	//Get template list

app/Http/Controllers/SMS/FeildController.php
<?php

namespace App\Http\Controllers\SMS;

use App\Http\Controllers\Controller;

use App\SmsModels\Feild;
use App\SmsModels\FeildType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;

class FeildController extends Controller
{

    /**
     * Create dynamic table along with dynamic fields
     *
     * @param       $table_name
     * @param array $fields
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function createTable($table_name, $fields = [])
    {
        // check if table is not already exists
        /*if (!Schema::hasTable($table_name)) {*/
            Schema::table($table_name, function (Blueprint $table) use ($fields, $table_name) {
                
                if (count($fields) > 0) {
                    foreach ($fields as $field) {
                        $table->{$field['type']}($field['name'])->after('id');;
                    }
                }
                
            });

            return response()->json(['message' => 'Given table has been successfully created!'], 200);
        /*}

        return response()->json(['message' => 'Given table is already existis.'], 400);*/
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $feilds = Feild::get();

        return view('admin.feilds.index')->with([
        'feilds'  => $feilds
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $feildtypes = Feildtype::where('status','ACTIVE')->get();
        return view('admin.feilds.create',compact('feildtypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*$validatedData = $this->validate($request, [
            "sms_template_form"  => "required|not_in:0" ,
            "fieldid"             => "required|array|min:1",
            "fieldid.*"           => "required|min:1",
            "fieldname"             => "required|array|min:1",
            "fieldname.*"           => "required|string|distinct|min:1",
            
        ]);*/
        $sms_template_form       = $request->sms_template_form;
        $fieldid            = $request->fieldid;
        $fieldname      = $request->fieldname;
        $i=0;
        $newdata = array();
        foreach ($fieldid as $k => $val) {
            if($k==$i){
                $newdata[$i]['fieldid'] = $val;
            }
            $i++;
        }
        $c=0;
        foreach ($fieldname as $ke => $value) {
            if($ke==$c) {
                $newdata[$c]['fieldname'] = $value;
            }
            $c++;
        }

        $fieldjsonData = json_encode($newdata);
        $data =array(
            'sms_template_form'              =>  $sms_template_form,
            'fielddata'         =>  $fieldjsonData
        );

        
        $feilds = Feild::create($data);
        // set dynamic table name according to your requirements

        $table_name = 'tbl_sms_templates';
        $i=1;
        // set your dynamic fields (you can fetch this data from database this is just an example)
        $jsonnewdata = json_decode($feilds->fielddata);
        foreach($jsonnewdata as $k => $value){
            
            $fields = [
                ['name' => str_replace(' ', '', $value->fieldname), 'type' => 'string']
                
            ];
            
            $i++;
            //return $this->createTable($table_name, $fields);
        }
        
        
        
        return redirect('admin/feilds')->withSuccess('Feild has been created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\feild  $feild
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $feilds = Feild::find($id);
        
        return view('admin.feilds.show', compact('feilds')); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\feild  $feild
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $feilds = Feild::find($id);
        $feildtypes = Feildtype::where('status','ACTIVE')->get();
        return view('admin.feilds.edit', compact('feilds','feildtypes')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\feild  $feild
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $feilds = Feild::find($id);
        $jsonnewdata = json_decode($feilds->fielddata);
        $sms_template_form       = $request->sms_template_form;
        $fieldid            = $request->fieldid;
        $fieldname      = $request->fieldname;
        $i=0;
        $newdata = array();
        foreach ($fieldid as $k => $val) {
            if($k==$i){
                $newdata[$i]['fieldid'] = $val;
            }
            $i++;
        }
        $c=0;
        foreach ($fieldname as $ke => $value) {
            if($ke==$c) {
                $newdata[$c]['fieldname'] = $value;
            }
            $c++;
        }
        $g=0;
            
        foreach ($jsonnewdata as $json1 => $column) {
            if($json1==$g) {
                $newdata[$g]['column'] = $column->fieldname;
            }
            $g++;
        }
        $h=0;
        
        foreach ($jsonnewdata as $json => $columnid) {
            if($json==$h) {
                $newdata[$h]['columnid'] = $columnid->fieldid;
            }
            $h++;
        }
        $fieldjsonData = json_encode($newdata);
        $feilds->sms_template_form =  $sms_template_form;
        $feilds->fielddata =  $fieldjsonData;
        $feilds->touch();        
        return redirect('/admin/feilds')->with('success', 'Feild updated!');
        
    }

    
}

resources/views/sms/issue/list.blade.php
@extends('layouts.default')
@section('title', 'Issue Panel List')
@section('content')

<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Issue Panel List</h4>
            <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url('admin/dashboard')}}">Dashboard</a></li>
                        <!-- <li class="breadcrumb-item"><a href="{{url('admin/sms/vouchers/create')}}">Add Voucher</a></li>
                        <li class="breadcrumb-item"><a href="{{route('voucher.upload.create')}}"><button class="btn btn-success btn-sm"    type="button" id="dropdownMenuButton">
                            <i class="fas fa-plus"></i> &nbsp; Upload Voucher Code
                            </button></a></li> -->
                        
                        
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
   
<!-- DataTales Example -->
<div class="card form-horizontal mt-3">
  <div class="card-body">
    @if(session()->get('success'))
    <div class="alert alert-success">
    {{ session()->get('success') }}  
    </div>
    @endif
    <br />
        
        <div class="filter_outer">
        <div class="card">
            <div class="card-body">
                
                <!-- Booking Filters Starts Here -->
                <div class="assign-book">
                    <div class="border-boking"></div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label>From Date</label>
                        <input type="date" name="from_date" id="from_date" class="form-control"
                            value="{{ isset($_GET['from_date']) ? $_GET['from_date'] : '' }}">

                    </div>
                    <div class="col-md-4">
                        <label>To Date</label>
                        <input type="date" name="to_date" id="to_date" class="form-control"
                            value="{{ isset($_GET['to_date']) ? $_GET['to_date'] : '' }}">
                    </div>
                    <div class="col-md-4">
                        <label>Select Campaign</label>
                        <select class="form-control select2" name="campaign_id[]" id="campaign_id"
                            data-placeholder="Select Campaign" multiple>
                            @forelse($campaigns as $camp)

                            <option value="{{$camp->id}}"
                                {{(isset($_GET['campaign_id']) && $_GET['campaign_id'] == $camp->id) ? 'Selected' : ''}}>
                                {{$camp->campaign_name}}</option>
                            @empty
                            <p>No Product List</p>
                            @endforelse
                        </select>
                        <div class="error1" style="display: none;">This field is required.</div>
                    </div>
                    <div class="col-md-4">
                      <label>Global Search</label>
                      <input type="text" name="global_search" id="global_search" class="form-control" value="{{ isset($_GET['global_search']) ? $_GET['global_search'] : '' }}" placeholder='Enter voucher code'>
                    </div>
                    
                    <div class="col-md-4">
                        <input type="button" class="btn btn-primary btn-block search_btn " id="voucher-filter" value="Search">
                        <input type="button" class="btn btn-info btn-block search_btn " id="voucher-refresh" value="Clear">
                    </div>
                </div>
            </div>
        </div>
    </div>
            
    <br />
    <!-- <h5 class="card-title">Campaign Type</h5> -->
    <div id="table_data">
        @include('sms.issue.pagination_data')
        <input type="hidden"  value="" id="hidden_page">
    </div>
    
  </div>

  <meta name="csrf-token" content="{{ csrf_token() }}">
  

    

<!-- /.container-fluid -->
</div>
<!-- End of Main Content -->
@stop

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
    
    
    $(document).ready(function(){
        $(document).on('click', '.pagination a', function(event){

            event.preventDefault(); 
            var page = $(this).attr('href').split('page=')[1];
            $("#hidden_page").val(page);
            var from_date = $('#from_date').val();
      
            var to_date = $('#to_date').val();
            var campaign_id = $( "#campaign_id").val();
            var global_search = $( "#global_search" ).val();
            fetch_data(page,from_date, to_date, campaign_id,global_search);
        });
        
        function fetch_data(page = '',from_date = '', to_date = '', campaign_id = '', global_search = '')
        {
          
            $.ajax({
            
                url:"/admin/sms/voucher/fetch_data?page="+page+"&from_date="+from_date+"&to_date="+to_date+"&campaign_id="+campaign_id+"&global_search="+global_search,
                beforeSend: function(){
                  // Show image container
                  $("#loading").show();
                },
                success:function(data)
                {
                    alert(data);
                  $('#table_data').html(data);
                },
                complete: function(){
                  $('#loading').hide();
                }
           
            });
        }
        var _token = $('input[name="_token"]').val();
        

        $('#voucher-filter').click(function(){
            
          var page = $("#hidden_page").val();
          
          var from_date = $('#from_date').val();
          var to_date = $('#to_date').val();
          var campaign_id = $("#campaign_id").val()
          var global_search = $("#global_search").val()
          if((from_date != '' &&  to_date != '') || campaign_id != '' || global_search != ''){
            fetch_data(page,from_date, to_date, campaign_id,global_search);
            }/*else{
               alert('Both Date is required');
            }*/
        });
    
        $('#voucher-refresh').click(function(){
          $('#from_date').val('');
          $('#to_date').val('');
          $('#global_search').val('');
          $("#campaign_id").val('').trigger('change');
    
          fetch_data();
        });
    
        
     
    });
    fetch_data();
</script>

resources/views/sms/issue/pagination_data.blade.php
<div class="table-responsive">
      <table class="table table-striped table-bordered" id="issue_table">
        <thead>
            <tr>
              <th>SN</th>
                <th>From</th>
                <th>Incoming Message Id</th>
                <th>Incoming Message</th>
                <th>Outgoing Message</th>
                <th>Status</th>
                <th>Created Date/Time</th>
                <th>Comments</th>
            </tr>
        </thead>
        <tbody>
          @forelse($data as $index=>$d)
          <tr>
              <td>{{$index + $data->firstItem()}}</td>
              <td>{{$d->id}}</td>
              <td>{{$d->incoming_msg->from}}</td>
              <td>{{$d->incoming_msg->message}}</td>
              <td>{{$d->outgoing_msg}}</td>
              <td>{{$d->status}}</td>
              <td>{{$camp->created_at->format('d M Y')}}/{{$camp->created_at->format('g:i A')}}</td>
              
              <td>
                  <div class="action">
                      <a href="{{ route('campaigns.show',$camp->id) }}">
                          <span>
                              <i class="fa fa-eye fa-primary"  title="View"></i>
                          </span>
                      </a>
                      <a href="{{ route('campaigns.edit',$camp->id)}}">
                          <span>
                              <i class="fa fa-pencil fa-primary"  title="Edit"></i>
                          </span>
                      </a>
                      
                  </div>
              </td>
              
          </tr>
          @empty
          <p>No Found Data</p>
          @endforelse
            
           
        </tbody>
        <tfoot>
            <th>SN</th>
                <th>From</th>
                <th>Incoming Message Id</th>
                <th>Incoming Message</th>
                <th>Outgoing Message</th>
                <th>Status</th>
                <th>Created Date/Time</th>
            </tr>
        </tfoot>
       
      </table>
      {!! $data->appends(Request::all())->links() !!}
    </div>