routes/web.php
	//Campaign type resource
	Route::resource('campaignextesions', 'SMS\campaign\CampaignExtensionController');

	//Offer type resource
	Route::resource('cashbacktypes', 'SMS\campaign\CashbackTypeController');
	
	//Offer type resource
	Route::resource('offers', 'SMS\campaign\OfferTypeController');
	
	//Get template list
	Route::get('campaigntype/get-template-list', 'SMS\campaign\CampaignTypeController@getTemplateList');
	

	//Get cashback list
	Route::get('cashbacktype/get-cashbacktype-list', 'SMS\campaign\CashbackTypeController@getCashbackTypeList');

	//Get status change
    Route::get('changeStatus', 'AuthController@changeStatus');

    //Campaign resource
	Route::resource('campaigns', 'SMS\campaign\CampaignController');
	
	//Campaign rule 
	Route::get('campaign/stats/{campaign_id}', ['as' => 'campaign.stats' , 'uses' => 'SMS\campaign\CampaignController@stats']);

	//Campaign rule 
	Route::get('campaign/rules/index/{campaign_id}', ['as' => 'campaign.rules.index' , 'uses' => 'SMS\rule\RuleController@index']);
	//Campaign rule show 
	Route::get('campaign/rules/show/{campaign_id}/{rule_id}', ['as' => 'campaign.rules.show' , 'uses' => 'SMS\rule\RuleController@show']);
	//Campaign rule edit 
	Route::get('campaign/rules/edit/{campaign_id}/{rule_id}', ['as' => 'campaign.rules.edit' , 'uses' => 'SMS\rule\RuleController@edit']);

	//Campaign rule create 
	
	Route::get('campaign/rules/create/{campaign_id}', ['as' => 'campaign.rules.create' , 'uses' => 'SMS\rule\RuleController@create']);
	//Campaign rule store 
	Route::post('campaign/rules/store/{campaign_id}', ['as' => 'campaign.rules.store' , 'uses' => 'SMS\rule\RuleController@store']);
	//Campaign rule update 
	Route::PATCH('campaign/rules/update/{rule_id}/{campaign_id}', ['as' => 'campaign.rules.update' , 'uses' => 'SMS\rule\RuleController@update']);

	//Campaign sms Template list
	Route::get('campaign/smstemp/index/{campaign_id}', ['as' => 'campaign.sms.index' , 'uses' => 'SMS\campaign\SmsController@index']);
	//Campaign sms Template show
	Route::get('campaign/sms/show/{campaign_id}/{sms_id}', ['as' => 'campaign.sms.show' , 'uses' => 'SMS\campaign\SmsController@show']);
	//Campaign sms Template edit
	Route::get('campaign/sms/edit/{campaign_id}/{sms_id}', ['as' => 'campaign.sms.edit' , 'uses' => 'SMS\campaign\SmsController@edit']);

	//Campaign sms Template create
	Route::get('campaign/sms/create/{campaign_type_id}/{template_id}', ['as' => 'campaign.sms.create' , 'uses' => 'SMS\campaign\SmsController@create']);
	//Campaign sms Template store
	Route::post('campaign/sms/store/{campaign_type_id}/{template_id}', ['as' => 'campaign.sms.store' , 'uses' => 'SMS\campaign\SmsController@store']);
	//Campaign sms Template update
	Route::PATCH('campaign/sms/update/{sms_id}/{campaign_id}', ['as' => 'campaign.sms.update' , 'uses' => 'SMS\campaign\SmsController@update']);

	//Campaign multioffercode sms Template Create

	Route::get('campaign/sms/createmultioffertemplate/{campaign_type_id}/{template_id}', ['as' => 'campaign.sms.createmultioffertemplate' , 'uses' => 'SMS\campaign\SmsController@createMultiOfferTemplate']);
	//Campaign sms Template store
	Route::post('campaign/sms/storemultioffertemplate/{campaign_type_id}/{template_id}', ['as' => 'campaign.sms.storemultioffertemplate' , 'uses' => 'SMS\campaign\SmsController@storeMultiOfferTemplate']);


	//Get field list by template id
	Route::get('get-field-template-list','SMS\campaign\CampaignController@getFieldTemplateList');

	//Feilds resource
	Route::resource('fields', 'SMS\FieldController');

	//SMS Template resource
	Route::resource('templates', 'SMS\TemplateController');

	//Rule Type resource
	Route::resource('ruletypes', 'SMS\rule\RuleTypeController');

	//Rule resource
	//Route::resource('rules', 'rule\RuleController');

	//Vocuhers resource
	Route::resource('vouchers', 'SMS\campaign\VoucherController');
	//Get template list
	Route::get('voucher/get-offer-list', 'SMS\campaign\VoucherController@getOfferList');
	//Get Offer Cashback list
	Route::get('voucher/get-offer-cashback', 'SMS\campaign\VoucherController@getOfferCashback');
	Route::get('voucher/fetch_data', 'SMS\campaign\VoucherController@fetch_data');
	Route::get('voucher/upload/create', ['as' => 'voucher.upload.create' , 'uses' => 'SMS\campaign\VoucherController@uploadVoucherCodeCreate']);
	Route::post('voucher/upload/store', ['as' => 'voucher.upload.store' , 'uses' => 'SMS\campaign\VoucherController@uploadVoucherCodeStore']);
	Route::get('voucher/all/edit', ['as' => 'voucher.all.edit' , 'uses' => 'SMS\campaign\VoucherController@allVoucherCodeEdit']);
	
	Route::post('voucher/all/update', ['as' => 'voucher.all.update' , 'uses' => 'SMS\campaign\VoucherController@allVoucherCodeUpdate']);
	Route::get('voucher/all/view', ['as' => 'delete.all.view' , 'uses' => 'SMS\campaign\VoucherController@allVoucherCodeDeleteView']);
	
	Route::post('voucher/all/viewUpdate', ['as' => 'delete.all.update' , 'uses' => 'SMS\campaign\VoucherController@allVoucherCodeDeleteUpdate']);

	Route::get('voucher/list', ['as' => 'voucher.list' , 'uses' => 'SMS\campaign\VoucherController@index']);

	//Campaign Feilds resource
	Route::resource('campaign-fields', 'SMS\campaign\CampaignFieldController');
	
	//Campaign rule create 
	Route::get('campaign/setting/create', ['as' => 'campaign.setting.create' , 'uses' => 'SMS\campaign\SettingController@create']);
	//Campaign rule store 
	Route::post('campaign/setting/store/{id?}', ['as' => 'campaign.setting.store' , 'uses' => 'SMS\campaign\SettingController@store']);
	
	//Campaign rule create 
	Route::get('campaign/redirect', ['as' => 'campaign.redirect' , 'uses' => 'SMS\campaign\SettingController@createRidrect']);
	//Campaign rule store 
	Route::post('campaign/redirectStore/{id?}', ['as' => 'campaign.redirectStore' , 'uses' => 'SMS\campaign\SettingController@storeRidrect']);


    //Incoming SMS 
	Route::get('report/incoming/list', ['as' => 'report.incoming.list' , 'uses' => 'SMS\campaign\ReportController@incomingReportList']);
	
	//Outgoing SMS 
	Route::get('report/outgoing/list', ['as' => 'report.outgoing.list' , 'uses' => 'SMS\campaign\ReportController@outgoingReportList']);
	
	//Whatsapp SMS 
	//Route::get('report/whatsapp/list', ['as' => 'report.whatsapp.list' , 'uses' => 'SMS\campaign\ReportController@whatsappReportList']);
	
	//Whatsapp SMS 
	Route::get('report/list/{id}', ['as' => 'report.whatsapp.list' , 'uses' => 'SMS\campaign\ReportController@whatsappImageView']);
	
    //reward List 
	Route::get('rewardcode/list', ['as' => 'rewardcode.list' , 'uses' => 'SMS\campaign\CampaignController@rewardcodeList']);
	
	//Issue Pnnel List 
	Route::get('issue/panel/list', ['as' => 'issue.panel.list' , 'uses' => 'SMS\campaign\ReportController@issuePanelList']);

	

	//reward List 
	Route::get('rewardcode/dashboard/list', ['as' => 'rewardcode.dashbaord.list' , 'uses' => 'SMS\campaign\CampaignController@rewardcodeDashboardList']);
	

	//reward List 
	Route::get('vouchercode/dashboard/list', ['as' => 'vouchercode.dashbaord.list' , 'uses' => 'SMS\campaign\CampaignController@vouchercodeDashboardList']);
    
	
});
Route::get('admin/outgoing/download-outgoing-excel', 'SMS\campaign\ReportController@allOutgoingDownload')->name('outgoing.download-outgoing-excel');

Route::get('admin/incoming/download-incoming-excel', 'SMS\campaign\ReportController@allIncomingDownload')->name('incoming.download-incoming-excel');
//Get field list by template id
Route::get('get-keyword-data','SMS\campaign\CampaignController@getKeywordData');
    
//Get field list by template id
Route::get('get-whatsapp-data','Whatsapp\WhatsAppController@getWhatsAppData');

//Whatsapp SMS 
Route::get('send-sms-template/{incoming_msg_id?}', 'SMS\campaign\SmsController@sendSmsTemplate');

//Whatsapp SMS 
Route::get('send-sms-second-template', 'SMS\campaign\SmsController@sendSmsSecondTemplate');

//Whatsapp SMS 
Route::get('send-sms-voucher-recharge-template', 'SMS\campaign\SmsController@sendVoucherRechargeBasedTemplate');
//Whatsapp SMS 
Route::get('send-whatsapp-template/{incoming_msg_id?}', 'Whatsapp\campaign\SmsController@sendWhatsappTemplate');


Route::get('validate-mobile-per-promotion/{campaign_id?}/{mobile_no?}', 'SMS\campaign\SmsController@validateMobilePerPromotion');


//Whatsapp


Route::group(['middleware'=>['admin'],'prefix'=> 'admin/whatsapp/'], function (){

	/*Route::get('register', 'AuthController@register');
	Route::post('post-register', 'AuthController@postRegister'); */
	Route::get('dashboard', 'Whatsapp\AuthController@dashboard'); 
/*	Route::get('logout', 'AuthController@logout');*/
    Route::post('dashboard', 'Whatsapp\AuthController@dashboard');
    //Campaign type resource
	Route::resource('campaignextesions', 'Whatsapp\campaign\CampaignExtensionController');
    //Issue Pnnel List 
	Route::get('issue/panel/list', ['as' => 'issue.panel.list' , 'uses' => 'Whatsapp\campaign\ReportController@issuePanelList']);

    //Offer type resource
	Route::resource('cashbacktypes', 'Whatsapp\campaign\CashbackTypeController');


	//Get cashback list
	Route::get('cashbacktype/get-cashbacktype-list', 'Whatsapp\campaign\CashbackTypeController@getCashbackTypeList');

	//Campaign type resource
	Route::resource('whatsappcampaigntypes', 'Whatsapp\campaign\CampaignTypeController');
	
	//Offer type resource
	Route::resource('whatsappoffers', 'Whatsapp\campaign\OfferTypeController');
	
	//Get template list
	Route::get('whatsappcampaigntype/get-template-list', 'Whatsapp\campaign\CampaignTypeController@getTemplateList');
	

	//Get status change
    Route::get('changeStatus', 'AuthController@changeStatus');

    //Campaign resource
	Route::resource('whatsappcampaigns', 'Whatsapp\campaign\CampaignController');
	
	//Campaign rule 
	Route::get('campaign/stats/{campaign_id}', ['as' => 'whatsappcampaign.stats' , 'uses' => 'Whatsapp\campaign\CampaignController@whatsappstats']);

	//Campaign rule 

app/Http/Controllers/MissedCall/FieldController.php
<?php

namespace App\Http\Controllers\MissedCall;

use App\Http\Controllers\Controller;

use App\MissedCallModels\Field;
use App\MissedCallModels\FieldType;
use App\MissedCallModels\FieldTemplate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;

class FieldController extends Controller
{

    /**
     * Create dynamic table along with dynamic fields
     *
     * @param       $table_name
     * @param array $fields
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function createTable($table_name, $fields = [])
    {
        // check if table is not already exists
        /*if (!Schema::hasTable($table_name)) {*/
            Schema::table($table_name, function (Blueprint $table) use ($fields, $table_name) {
                
                if (count($fields) > 0) {

                    foreach ($fields as $field) {

                        $table->string(str_replace(' ','_', $field->fieldname))->after('id');
                        $table->string(str_replace(' ','_', $field->templateid))->after(str_replace(' ','_', $field->fieldname));
                    }
                }
                
            });

            return redirect('admin/feilds')->withSuccess('Feild has been created successfully!');
        /*}

        return response()->json(['message' => 'Given table is already existis.'], 400);*/
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $fields = Field::get();

        return view('missedcall.fields.index')->with([
        'fields'  => $fields
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $fieldtypes = Fieldtype::where('status','ACTIVE')->get();
        
        return view('missedcall.fields.create',compact('fieldtypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $validatedData = $this->validate($request, [

            "fieldid.*" => 'required|not_in:0',
            "field_name.*" => 'required|not_in:0',
            "field_name" => "required|unique:sms_tbl_fields",
            'module_name' =>'required|in:1,2' 
            
            
        ]);
        
        $fieldid            = $request->fieldid;
        $fieldname      = $request->field_name;
        $modulename      = $request->module_name;

        foreach ($fieldid as $i => $val) {
            $feilds = new Field;
            $feilds->module_name = $modulename;
            $feilds->field_name = $fieldname[$i];
            $feilds->field_slug = str_replace(' ', '_', $fieldname[$i]);
            $feilds->field_type_id = $val;
            $feilds->save();

            /*$FieldTemplate = new FieldTemplate;

            $FieldTemplate->field_id = $feilds->id;
            $FieldTemplate->keyword = str_replace(' ','_', $fieldname)[$i];
            $FieldTemplate->save();*/
        }

        

        
        
        // set dynamic table name according to your requirements

        //$table_name = 'tbl_sms_templates';
        /*$i=1;*/
        // set your dynamic fields (you can fetch this data from database this is just an example)
        //$jsonnewdata = json_decode($feilds->fielddata);
        //dd($jsonnewdata);
        /*foreach($jsonnewdata as $k => $value){*/
            
            //$fields = $jsonnewdata;
            
           /* $i++;*/
            //return $this->createTable($table_name, $fields);
        /*}
        */
        
        
        return redirect('admin/missedcall/missedcallfields')->withSuccess('Feild has been created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\feild  $feild
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $fields = Field::find($id);
        
        return view('missedcall.fields.show', compact('fields')); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\feild  $feild
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $fields = Field::find($id);
        $fieldtypes = Fieldtype::where('status','ACTIVE')->get();
        return view('missedcall.fields.edit', compact('fields','fieldtypes')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\feild  $feild
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $feilds = Field::find($id);
        
        $feilds->field_type_id        = $request->fieldid;
        $feilds->field_name      = $request->field_name;
        $feilds->field_slug = str_replace(' ', '_', $request->field_name);
        $feilds->touch();        
        return redirect('/admin/missedcall/missedcallfields')->with('success', 'Feild updated!');
        
    }

    
}

app/Http/Controllers/SMS/campaign/CashbackTypeController.php
<?php

namespace App\Http\Controllers\SMS\campaign;

use App\SmsModels\CashbackType;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class CashbackTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cashbackTypes = CashbackType::get();

        return view('sms.cashback_type.index')->with([
        'cashbackTypes'  => $cashbackTypes
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sms.cashback_type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validatedData = $this->validate($request, [
            'name'      => 'required|unique:sms_tbl_offers',
            
            
        ]);

        CashbackType::create($validatedData);

        return redirect('admin/sms/cashbacktypes')->withSuccess('Cashback Types has been created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\CampaignType  $campaignType
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cashbackType = CashbackType::find($id);
        return view('sms.cashback_type.show',compact('cashbackType'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\CampaignType  $campaignType
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $cashbackType = CashbackType::find($id);
       
        return view('sms.cashback_type.edit', compact('cashbackType'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\CampaignType  $campaignType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $request->validate([
            'name'=>'required',
            
            
        ]);        
        $cashbackType = CashbackType::find($id);
        $cashbackType->name =  $request->get('name');
        $cashbackType->touch();        
        
        return redirect('/admin/sms/cashbacktypes')->with('success', 'Cashback Types updated!');
    }

    public function getCashbackTypeList()
    {
        $cashbacktypes = CashbackType::where(['status'=>'ACTIVE'])->pluck("name","id");

    
        return response()->json($cashbacktypes);
    }

}

resources/views/sms/fields/create.blade.php
@extends('layouts.default')
@section('title', 'Fields Create')
@section('content')
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Fields Create</h4>
            <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url('admin/sms/fields')}}">Back</a></li>
                        
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
@if ($errors->any())
<div class="alert alert-danger">
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
 </ul>
</div><br/>
@endif
<form action="{{ route('fields.store') }}" method="POST" class="form-horizontal mt-3" id="fieldForm">
  {{ csrf_field() }}
  <div class="card">
    <div class="card-body">
      
      
      
        <div class="col-md-4">
            <label for="hue-demo" style="margin-right: 20px;">Select Module </label>
            <div class="form-check form-check-inline">
                <input type="radio" class="form-check-input"
                id="customControlValidation5" name="module_name" value="{{old('module_name') ?  old('module_name') : '1'}}">
                


                <label class="form-check-label mb-0" for="customControlValidation5">Template</label>
            </div>
            <div class="form-check form-check-inline">
                <input type="radio" class="form-check-input"
                id="customControlValidation6" name="module_name" value="{{old('module_name') ?  old('module_name') : '2'}}">
                <label class="form-check-label mb-0" for="customControlValidation6">Campaign</label>
            </div>
            @if ($errors->has('module_name'))
            <div class="invalid-feedback" style="display:block;">
                <strong>{{ $errors->first('module_name') }}.</strong>
            </div>
            @endif
        </div>
        <div class="row wrapper">
            <div class="col-md-8 cloningform">                  
                <div class="row">
                    <div class="form-group col-md-4" id="fieldtype">
                        <label>Field Type</label>
                        <select class="form-select shadow-none fieldid form-control" name="fieldid[]" id="fieldid">
                        <option value="">Please Select</option>
                        @forelse($fieldtypes as $type)
                        
                        <option value="{{$type->id}}" {{old('fieldid') == $type->id ? 'Selected' : ''}}>{{$type->name}}</option>
                        
                        @empty
                        <p>No Found Result</p>
                        @endforelse
                        </select>
                  
                        @error('fieldid.*')
                        <div class="invalid-feedback" style="display:block;">
                            <strong>{{ $message }}</strong>
                        </div>
                        
                        @enderror
                </div>
                <div class="form-group col-md-4">
                  <label for="hue-demo">Placeholder OR Label</label>
                  <input type="text" id="hue-demo" class="form-control demo fieldname" name="field_name[]" data-control="hue"
                      placeholder="Enter Feild label" value="{{ old('fieldname') }}">
                    @error('field_name.*')
                        <div class="invalid-feedback" style="display:block;">
                            <strong>{{ $message }}</strong>
                        </div>
                        
                    @enderror
                </div>
                
                <div class="form-group col-md-4 addbtn">
                  <label>&nbsp;</label><br>
                  <a class="btn btn-default add_item">Add</a>
                </div>
            </div>
          </div>
        </div>
      
      
    </div>
    <div class="border-top">
      <div class="card-body">
        <button type="submit" class="btn btn-success text-white">Save</button>
        <button type="reset" class="btn btn-primary">Reset</button>
        <!-- <button type="submit" class="btn btn-info">Edit</button> -->
        <button type="submit" class="btn btn-danger text-white">Cancel</button>
      </div>
    </div>
  </div>
</form>

<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->
@stop

resources/views/sms/fields/edit.blade.php
@extends('layouts.default')
@section('title', 'Fields Create')
@section('content')


<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Fields Edit</h4>
            <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        
                        <li class="breadcrumb-item"><a href="{{url('admin/sms/fields')}}">Back</a></li>
                        
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
   <!-- Start Page Content -->
   <!-- ============================================================== -->
  @if ($errors->any())
     <div class="alert alert-danger">
       <ul>
           @foreach ($errors->all() as $error)
             <li>{{ $error }}</li>
           @endforeach
       </ul>
     </div><br />
  @endif
  
  <form action="{{ route('fields.update', $fields->id) }}" method="POST" class="form-horizontal mt-3" id="">
    @method('PATCH') 
    {{ csrf_field() }}
    <div class="card">
      <div class="card-body">
        <div class="wrapper">
            <div class="row cloningform">
              <div class="col-md-8">
                  <div class="row">
                        <div class="form-group col-md-6" id="fieldtype">
                            <label>Field Type</label>
                            <select class="select2 form-select shadow-none fieldid" style="width: 100%; height:36px;" name="fieldid" id="">
                                <option value="">Please Select</option>
                                @forelse($fieldtypes as $type)
                
                                
                                <option value="{{$type->id}}" {{$fields->field_type_id==$type->id ? 'Selected' : ''}}>{{$type->name}}</option>
                                
                                @empty
                                <p>No Found Result</p>
                                @endforelse
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                          <label for="hue-demo">Placeholder OR Label</label>
                          <input type="text" id="hue-demo" class="form-control demo" name="field_name" data-control="hue"
                              placeholder="Enter Same Mobile Number Allowed" value="{{ $fields->field_name }}" id="fieldname">
                        </div>
                  </div>
              </div>
            </div>
            
          </div>
      </div>
        <div class="border-top">
        <div class="card-body">
          <button type="submit" class="btn btn-success text-white">Update</button>
          <button type="reset" class="btn btn-primary">Reset</button>
          <!-- <button type="submit" class="btn btn-info">Edit</button> -->
          <button type="submit" class="btn btn-danger text-white">Cancel</button>
        </div>
      </div>
      </div>
    </div>
  </form>
  
   <!-- ============================================================== -->
   <!-- End PAge Content -->
   <!-- ============================================================== -->
   
@stop

resources/views/sms/fields/show.blade.php
@extends('layouts.default')
@section('title', 'Show Fields')
@section('content')
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Fields Details</h4>
            <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        
                        <li class="breadcrumb-item"><a href="{{url('admin/sms/fields')}}">Back</a></li>
                        
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="row form-horizontal mt-3">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
          <h5 class="card-title mb-0">fields Details</h5>
      </div>
      <div class="table-responsive">
          <table class="table">
            <tbody>
               
                <tr>
                    <td>Field Name</td>
                    <td>{{$fields->field_name}}</td>
                </tr>
                <tr>
                    <td>Created By</td>
                    <td>{{isset($fields->created_user['name']) ? $fields->created_user['name'] : 'NA'}}</td>
                </tr>
                <tr>
                    <td>Updated By</td>
                    <td>{{isset($fields->updated_user['name']) ? $fields->updated_user['name'] : 'NA'}}</td>
                </tr>
                <tr>
                    <td>Created Date/Time</td>
                    <td>{{$fields->created_at->format('d M Y')}}/{{$fields->created_at->format('g:i A')}}</td>
                </tr>
                <tr>
                    <td>Updated Date/Time</td>
                    <td>{{$fields->created_at->format('d M Y')}}/{{$fields->created_at->format('g:i A')}}</td>
                </tr>
                <tr>
                    <td>Status</td>
                    <td>{{$fields->status}}</td>
                </tr>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>
@stop